// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwxgappgzhejfcegfjhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3eGdhcHBnemhlamZjZWdmamhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTIzNDEsImV4cCI6MjA2MTkyODM0MX0.QrVYjL3s6bQwR90F3uUHhvP7t6D3j6kxpV_c7foouKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);